export const SEARCH_TITLE_STARTED = "SEARCH_TITLE_STARTED";
export const SEARCH_TITLE_FAILURE = "SEARCH_TITLE_FAILURE";
export const SEARCH_TITLE_SUCCESS = "SEARCH_TITLE_SUCCESS";

export const SEARCH_ALL_STARTED = "SEARCH_ALL_STARTED";
export const SEARCH_ALL_FAILURE = "SEARCH_ALL_FAILURE";
export const SEARCH_ALL_SUCCESS = "SEARCH_ALL_SUCCESS";
